version: '3'
services:
  example:
    image: denoland/deno:alpine
    volumes:
      - ./:/app
    command:
      - /bin/sh
      - -c
      - deno eval 'import {transform} from "npm:@swc/core@1.3.101";console.log(await transform("if(true){}"));'